# Generated by Django 4.2.2 on 2023-07-02 05:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Posts',
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': '게시판', 'verbose_name_plural': '게시판'},
        ),
        migrations.AlterModelTable(
            name='posts',
            table='게시판',
        ),
    ]
